name: GitHub-Profile-3D-Contrib

on:
  schedule: 
    - cron: "0 18 * * *" #每天18:00触发工作流
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_README }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -A .
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "generated"
            git push
          fi
